### ISSUE TITLE
NamespaceError: The operation is not allowed by Namespaces in XML

### ISSUE THREAD

**Issue by bensooraj** [oozcitak/xmlbuilder2#53] opened 2020-09-13 19:20 UTC
**Describe the bug**
When trying to build the xml with namespaces as attributes, I get the following error:

```sh
/Desktop/NodeJS/xml_bug_report/node_modules/xmlbuilder2/lib/builder/XMLBuilderImpl.js:707
                finally { if (e_2) throw e_2.error; }
                                   ^

Error [NamespaceError]: The operation is not allowed by Namespaces in XML. [XMLNS] Qualified name includes a prefix but the namespace is null.
    at NamespaceError.DOMException [as constructor] (/Desktop/NodeJS/xml_bug_report/node_modules/@oozcitak/dom/lib/dom/DOMException.js:28:28)
    at new NamespaceError (/Desktop/NodeJS/xml_bug_report/node_modules/@oozcitak/dom/lib/dom/DOMException.js:138:23)
    at Object.namespace_validateAndExtract (/Desktop/NodeJS/xml_bug_report/node_modules/@oozcitak/dom/lib/algorithm/NamespaceAlgorithm.js:58:15)
    at ElementImpl.setAttributeNS (/Desktop/NodeJS/xml_bug_report/node_modules/@oozcitak/dom/lib/dom/ElementImpl.js:251:37)
    at XMLBuilderImpl._updateNamespace (/Desktop/NodeJS/xml_bug_report/node_modules/xmlbuilder2/lib/builder/XMLBuilderImpl.js:698:32)
    at XMLBuilderImpl.att (/Desktop/NodeJS/xml_bug_report/node_modules/xmlbuilder2/lib/builder/XMLBuilderImpl.js:201:18)
    at Object.<anonymous> (/Desktop/NodeJS/xml_bug_report/main.js:15:6)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32) {
  name: 'NamespaceError'
}
```

This works perfectly fine with `xmlbuilder2@2.1.2`, however any minor or major versions after that throws the above error.

**To Reproduce**
Please run the following snippet to reproduce the behaviour:
```js
// main.js
const { create } = require('xmlbuilder2');
const createXMLNode = create;

let requestXML = "";

requestXML = createXMLNode({ version: "1.0", encoding: "UTF-8" })
    .ele("tns1:READ_WRITE_REQ_GBO")
    .att("xmlns:wsa", "http://www.w3.org/2005/08/addressing")
    .att("xmlns:cct", "urn:un:unece:uncefact:documentation:standard:CoreComponentType:2")
    .att("xmlns:ccts", "urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2")
    .att("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance")
    .att("xmlns:cmn", "http://single.xxyyzz.com/schema/common/v1")
    .att("xmlns:tns", "http://single.xxyyzz.com/schema/vbo/order/service-order/v1")
    .att("xmlns:extvbo", "http://single.xxyyzz.com/schema/extension/vbo/order/service-order/v1")
    .att("xmlns:tns1", "http://single.xxyyzz.com/schema/order/service/v1")
    .att("xmlns:vbm", "http://single.xxyyzz.com/schema/vbm/order/service-order/v1")
    .att("xmlns:hed", "http://single.xxyyzz.com/contract/vho/header/v1")
    .att("xmlns:flt", "http://single.xxyyzz.com/contract/vfo/fault/v1")
    .att("xmlns:bf", "http://docs.oasis-open.org/wsrf/bf-2")

let headerNodeXML = createXMLNode()
    .ele("Header") // Header
    .ele("RouteInfo") // RouteInfo
    .ele("hed:Route")
    .ele("hed:ID").txt("ServiceOrder.Create").up()
    .ele("hed:Keys")
    .ele("hed:Key").up().up().up().up()
    .ele("Correlation") // Correlation
    .ele("hed:ConversationID").txt("TransactionUUID").up().up()
    .ele("Destination") // Destination
    .ele("hed:Operator").txt("").up()
    .ele("hed:Division").txt("").up()
    .ele("hed:System").txt("FES.CreateFeasibility").up().up()
    .ele("Source") // Source
    .ele("hed:Division").txt("").up()
    .ele("hed:System").txt("ESMS").up().up().up();

requestXML = requestXML.import(headerNodeXML);

requestXML = requestXML.end({ prettyPrint: true });
console.log(requestXML)
```

**Expected behavior**
The expected output is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<tns1:READ_WRITE_REQ_GBO xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:cct="urn:un:unece:uncefact:documentation:standard:CoreComponentType:2" xmlns:ccts="urn:un:unece:uncefact:documentation:standard:CoreComponentsTechnicalSpecification:2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cmn="http://single.xxyyzz.com/schema/common/v1" xmlns:tns="http://single.xxyyzz.com/schema/vbo/order/service-order/v1" xmlns:extvbo="http://single.xxyyzz.com/schema/extension/vbo/order/service-order/v1" xmlns:tns1="http://single.xxyyzz.com/schema/order/service/v1" xmlns:vbm="http://single.xxyyzz.com/schema/vbm/order/service-order/v1" xmlns:hed="http://single.xxyyzz.com/contract/vho/header/v1" xmlns:flt="http://single.xxyyzz.com/contract/vfo/fault/v1" xmlns:bf="http://docs.oasis-open.org/wsrf/bf-2">
  <Header>
    <RouteInfo>
      <hed:Route>
        <hed:ID>ServiceOrder.Create</hed:ID>
        <hed:Keys>
          <hed:Key/>
        </hed:Keys>
      </hed:Route>
    </RouteInfo>
    <Correlation>
      <hed:ConversationID>TransactionUUID</hed:ConversationID>
    </Correlation>
    <Destination>
      <hed:Operator/>
      <hed:Division/>
      <hed:System>FES.CreateFeasibility</hed:System>
    </Destination>
    <Source>
      <hed:Division/>
      <hed:System>ESMS</hed:System>
    </Source>
  </Header>
</tns1:READ_WRITE_REQ_GBO>
``` 

**Version:**
 - node.js: [v12.13.0]
 - xmlbuilder2 [2.3.1]

**Additional context**

This appears to be similar to the issue at #51. I am opening a new one because you had closed it with a fix 21263b3.

I did try out the fix using `npm i https://github.com/oozcitak/xmlbuilder2#21263b3`, however the sample code failed with the same error.

**Comment by oozcitak** [comment] 2020-09-14 10:28
Seems to be a duplicate of #51. I just rolled out `v2.4.0` which should fix both issues.

**Closed** 2020-09-14 10:28 UTC
Labels: bug

**Comment by bensooraj** [comment] 2020-09-14 11:07
Thank you so much @oozcitak.

I have verified, this issue is fixed! Thanks!
