### ISSUE TITLE
Add param in convert method for group attributes

### ISSUE THREAD

**Issue by gpyshenko** [oozcitak/xmlbuilder2#32] opened 2020-07-10 07:32 UTC
I think we need to add a parameter that will include grouping attributes in the ` @ ' key even if there is only one attribute. This is convenient so that after receiving the result, you do not need to make extra checks, and the result will be expected.

**Comment by oozcitak** [comment] 2020-07-10 08:16
Duplicate of #31

**Closed by oozcitak** 2020-07-10 08:16 UTC
Labels: enhancement

**Comment by gpyshenko** [comment] 2020-07-10 08:20
Here i suggest add parameter.

> Duplicate of #31 
In this issue bug.

**Comment by oozcitak** [comment] 2020-07-10 10:23
There is already a parameter for grouping: https://oozcitak.github.io/xmlbuilder2/serialization.html#js-object-and-map-serializers
From your #31 it doesn't seem to work as intended, so I'm looking into it.

**Comment by gpyshenko** [comment] 2020-07-10 10:34
> There is already a parameter for grouping: https://oozcitak.github.io/xmlbuilder2/serialization.html#js-object-and-map-serializers
> From your #31 it doesn't seem to work as intended, so I'm looking into it.

Grouping is work in `create()` method with `end()` method, but `convert()` method has not `end()` method.

**Comment by oozcitak** [comment] 2020-07-10 10:41
You can pass serialization options as its last argument, see: https://oozcitak.github.io/xmlbuilder2/builder-functions.html#convert

```js
const obj = convert({ convert: { text: 'value' } }, input, { format: 'object', group: true })
```

**Comment by oozcitak** [comment] 2020-07-10 10:49
For future reference `convert` is simply `create` followed by `end`. It passes its arguments directly to these functions:
```js
convert(createOptions, input, serializationOptions);
// is equivalent to
create(createOptions, input).end(serializationOptions);
```
It is just syntactic sugar really.

**Comment by gpyshenko** [comment] 2020-07-10 11:08
Thank you. I dont know it was possible)) I think this example add in documentation. If this example exist in documentation, i apologize.
