### ISSUE TITLE
HTML Entities are unescaped when creating using json object

### ISSUE THREAD

**Issue by chris-rudmin** [oozcitak/xmlbuilder2#115] opened 2021-12-21 04:37 UTC
**Describe the bug**
HTML Entities are unescaped when creating xml using a json object

**To Reproduce**
```
create().ele({
    'foo': '&apos;&quot;&#xA9;&#x2117;&#x2122;'
}).end()

// <?xml version="1.0"?><foo>'"©℗™</foo>
````

```
create().ele('foo').txt('&apos;&quot;&#xA9;&#x2117;&#x2122;').end()
// <?xml version="1.0"?><foo>&apos;&quot;&#xA9;&#x2117;&#x2122;</foo>
````

**Expected behavior**
text should remain as it was input and should be consistent with the chained builder

**Version:**
 - node.js: [14.18.1]
 - xmlbuilder2 [3.0.2]

**Additional context**

**Comment by universalhandle** [comment] 2023-04-24 21:59
This looks like a duplicate of various issues that have been opened related to ampersand encoding (see https://github.com/oozcitak/xmlbuilder2/issues/105, https://github.com/oozcitak/xmlbuilder2/issues/109, https://github.com/oozcitak/xmlbuilder2/issues/110). I believe this to be fixed with the release of [v3.1.0](https://github.com/oozcitak/xmlbuilder2/releases/tag/v3.1.0). Please reopen if you can still reproduce after upgrading.

**Closed by universalhandle** 2023-04-24 21:59 UTC
Labels: bug
