### ISSUE TITLE
When converting from xml string to js object, `&` might be double escaped

### ISSUE THREAD

**Issue by chuanqisun** [oozcitak/xmlbuilder2#98] opened 2021-07-20 05:28 UTC
**Describe the bug**

```js
const { create } = require('xmlbuilder2');

const result = create(
  `<description>I'm &lt;b&gt;bold&lt;/b&gt;</description>`
).end({ format: 'object' });
console.log(result);
// Actual { description: "I'm &amp;lt;b&amp;gt;bold&amp;lt;/b&amp;gt;" }
// Expected { description: "I'm <b>bold</b>" } Or { description: "I'm &lt;b&gt;bold&lt;/b&gt;" }

```

**To Reproduce**
https://stackblitz.com/edit/node-rmf2h7?devtoolsheight=33&file=index.js
run `node index.js` to produce output

**Expected behavior**
I might have misunderstood your design. I just thought the parser should either preserve the original string or unescape it. 
Double escape the `&` seems to be strange behavior.

**Version:**
 - node.js: 14.16.0
 - xmlbuilder2 2.4.1

**Additional context**
I'm using your util to build the next major version of [an RSS feed reader + generator](https://github.com/osmoscraft/osmosfeed). I'm following [these examples](https://cyber.harvard.edu/rss/encodingDescriptions.html) to handle several html encoding scenarios. My primary use case is xml -> json but my tool will also handle feed generation so I really hope I can get the bi-directional conversion working with a single library. Thanks for the high quality work!

**Comment by chuanqisun** [comment] 2021-07-20 05:32
Might be related to #82 and #88. Feel free to close as dupes if they are caused  by the same issue.

**Comment by oozcitak** [comment] 2021-07-27 15:55
Yes, this is a duplicate of #82 and #88. An interim fix might be to pass the `noDoubleEncoding` flag with `end` if that works for you. I'll fix this in the underlying DOM library: https://github.com/oozcitak/dom/issues/7

**Closed by oozcitak** 2021-07-27 15:55 UTC
Labels: bug

**Comment by kernwig** [comment] 2021-07-28 19:36
The `noDoubleEncoding: true` option had no effect for me when parsing XML text into Javascript object.
