### ISSUE TITLE
DOM textContent returns encoded text

### ISSUE THREAD

**Issue by paulish** [oozcitak/xmlbuilder2#88] opened 2021-05-17 05:29 UTC
**Describe the bug**

The textContent property of elemenet does not decode encoded text (&gt; &lt;, etc).

**To Reproduce**
I compare 2 dom parsers. The first is from xmlbuilder2 and the second is from the xmldom library.
```javascript
const { create } = require("xmlbuilder2");
const fs = require("fs");
const { DOMParser } = require('xmldom')


const xmlStr = fs.readFileSync("./1.xml", "utf-8");
const xml = create(xmlStr);
const els1 = xml.node.getElementsByTagName("text");
for (let i = 0; i < els1.length; i++) {
    console.log(i, els1[i].textContent);
}

const doc = new DOMParser().parseFromString(xmlStr);
const els2 = doc.documentElement.getElementsByTagName("text");
for (let i = 0; i < els2.length; i++) {
    console.log(i, els2[i].textContent);
}
```
The result of the program is the following output in the console:

``` 
0 &lt;data&gt;
1 <data>
0 <data>
1 <data>
```

**Expected behavior**
Expected output is:
``` 
0 <data>
1 <data>
0 <data>
1 <data>
```

**Version:**
 - node.js: 12.22.1
 - xmlbuilder2 2.4.1

**Comment by oozcitak** [comment] 2021-05-17 10:03
Can you post the content of `1.xml` please?

**Comment by paulish** [comment] 2021-05-17 10:05
Sorry :)

```xml
<?xml version="1.0" encoding="utf-8"?>
<root>
  <text>&lt;data&gt;</text>
  <text><![CDATA[<data>]]></text>
</root>
```

**Comment by oozcitak** [comment] 2021-07-27 15:53
Duplicate of #82

**Closed by oozcitak** 2021-07-27 15:53 UTC
Labels: bug
