### ISSUE TITLE
Invalid Character replacement does not work for element names

### ISSUE THREAD

**Issue by solomon911** [oozcitak/xmlbuilder2#39] opened 2020-07-15 06:10 UTC
**Describe the bug**
Invalid Character replacement does not work for element names

**To Reproduce**
Attaching a stackblitz example: 
https://stackblitz.com/edit/js-xmlbuilder2-invchar?file=index.js 

In the example, the element name is '--name',

**Expected behavior**
 since '-' is invalid character, it should be replaced with ''

**Version:**
 - node.js: [x.x.x]
 - xmlbuilder2 [2.2.0]

**Comment by oozcitak** [comment] 2020-07-15 09:36
`invalidCharReplacement` only replaces invalid characters defined in the [XML spec](https://www.w3.org/TR/xml/#charsets):

> Char	   ::=   	#x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]

The check is limited to those characters only because performance-wise it would be very expensive to check all productions in the spec. In your case the `-` character is not allowed at the start of a name production, but it is valid elsewhere. If we wanted to implement this:

1. `--name` -> regex -> first `-` is invalid, replace it -> `-name`
1. `-name` -> regex -> first `-` is invalid, replace it -> `name`
3. `name` -> regex -> no matches -> continue

So even for such a simple string we would need three regex matches. This would degrade performance a lot. And considering some complex productions in the spec, there will probably be edge cases that would need to be handled separately.

So this is by design and won't be fixed.

**Closed by oozcitak** 2020-07-15 09:36 UTC
Labels: bug
